name: CI
on:
  workflow_dispatch:
  pull_request:

  # triggering CI default branch improves caching
  # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
  push:
    branches:
      - main
      -
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'pan-domain-node/.nvmrc'
          cache: npm
          cache-dependency-path: 'pan-domain-node/package-lock.json'

      - name: JS Build
        run: |
          pushd pan-domain-node

          npm ci
          npm run build
          npm test

          popd

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'sbt'

      - name: Scala Build
        run: sbt clean +test
