name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: 'pan-domain-node/package-lock.json'

      - name: JS Build
        run: |
          pushd pan-domain-node

          npm ci
          npm run build
          npm test

          popd

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'sbt'

      - name: Scala Build
        run: sbt clean +test
