name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian
      SKIP_NODE: false
      NODE_VERSION_FILE: ./pan-domain-node/.nvmrc
      EXCLUDE: hmac-examples
      
      
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
